---
- name: get server stats
  hosts: all
  tasks:
    - name: check memory
      command: "free -m"
      register: result
    - name: check disk
      command: "df -h"
      register: result
    - name: display the output
      debug:
        var: result
    