---
all:
  hosts:
    host1:
      ansible_host: 10.108.0.4
    host2:
      ansible_host: 10.108.0.6
    host3:
      ansible_host: 10.108.0.5
  children:
    centos:
      hosts:
        10.108.0.4:
        10.108.0.6:
    ubuntu:
      hosts:
        10.108.0.5: