---
## Install and configure Wordpress in Centos7
## Play1: Setup Apache
- name: install apache in Centos7
  hosts: localhost
  become: true
  tasks:
    - name: Modify Selinux
      lineinfile:
        dest: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
    - name: install repos on server
      yum: 
        name: 
          - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
          - epel-release
        state: latest
    - name: enabling repo
      command: yum-config-manager --enable remi-php74
    - name: install dependants
      yum: 
        name: "{{ packages }}"
      vars:
        packages: 
        - yum-utils
        - php
        - php-common
        - php-mysql
        - php-cli
        - php-curl
        - php-gd
        - php-mbstring
        - php-xml
        state: latest
    - name: install and enable Apache
      yum: 
        name: 
          - httpd
          - wget
        state: latest
    - name: enable Apache
      systemd: name=httpd enabled=yes state=restarted

## Play2: Install&Unarchive Wordpress
- name: Download wordpress
  hosts: localhost
  tasks:
    - name: 
      get_url:
        url: http://wordpress.org/latest.tar.gz
        dest: /tmp/latest.tar.gz
    - name: unarchive
      unarchive:
        src: /tmp/latest.tar.gz
        dest: /tmp
        remote_src: yes
    - name: copy the files and change the ownership  
      copy:
        src: /tmp/wordpress/
        dest: /var/www/html
        remote_src: true
        owner: apache
        group: apache


      


    
  

    